services:

  certbot:
   
   image: certbot/certbot:latest
   command:   certonly --webroot --webroot-path /var/www/certbot/  -d ${DOMAIN} --email ${EMAIL} 
   volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
            
