# rasax specific settings
rasax:
  # initialUser is the user which is created upon the initial start of Rasa Enterprise
  initialUser:
    # username specifies a name of this user - defaults to "admin"
    username: 'admin'
    # password for the Rasa Enterprise user
    password: 'admin'
  # passwordSalt Rasa Enterprise uses to salt the user passwords
  passwordSalt: ${PASSWORD_SALT} 
  # token Rasa Enterprise accepts as authentication token from other Rasa services
  token: ${RASA_X_TOKEN} 
  # jwtSecret which is used to sign the jwtTokens of the users
  jwtSecret:  ${JWT_SECRET} 
  tag: "1.1.3"
# ingress:
#   # if you don't use Ingress, this step can be skipped.
#   enabled: true
#   # path: /
rasa: #  Settings common for all Rasa containers
  # token Rasa accepts as authentication token from other Rasa services
  token: ${RASA_TOKEN} 
  # versions:
  rasaProduction:
  #     # the rasa production deployment is disabled by default.
  #     enabled: true 
    external:
      enabled: true 
      url: 'http://rasa.rasa.svc'
      port: 5005
  tag: "3.1.1"

# RabbitMQ specific settings
rabbitmq:
  # rabbitmq settings of the subchart
  auth:
    # password which is used for the authentication
    password: 'YiTL7oUmYVCuRu'
# global settings of the used subcharts
global:
  # postgresql: global settings of the postgresql subchart
  postgresql:
    # postgresqlPassword is the password which is used when the postgresqlUsername equals "postgres"
    postgresqlPassword: 'VnteG2hJCdSBQi'
  # redis: global settings of the redis subchart
  redis:
    # password to use in case there no external secret was provided
    password: '5Yo7hBX77CrKQM'
# 
debugMode: 'true'